// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {

    "Main settings": {
        "en": "Main settings",
        "de": "Haupteinstellungen",
        "ru": "Основные настройки",
        "pt": "Configurações principais",
        "nl": "Belangrijkste instellingen",
        "fr": "Réglages principaux",
        "it": "Impostazioni principali",
        "es": "Ajustes principales",
        "pl": "Ustawienia główne"
    },
    "settings": {
        "en": "settings",
        "de": "Einstellungen",
        "ru": "настройки",
        "pt": "configurações",
        "nl": "instellingen",
        "fr": "paramètres",
        "it": "impostazioni",
        "es": "ajustes",
        "pl": "ustawienia"
    },
    "Find Devices": {
        "en": "Find Devices",
        "de": "Geräte suchen",
        "ru": "Поиск устройств",
        "pt": "Encontrar dispositivos",
        "nl": "Vind apparaten",
        "fr": "Trouver des périphériques",
        "it": "Trova dispositivi",
        "es": "Encontrar dispositivos",
        "pl": "Znajdź urządzenia"
    },
    "Name": {
        "en": "Name",
        "de": "Name",
        "ru": "имя",
        "pt": "Nome",
        "nl": "Naam",
        "fr": "prénom",
        "it": "Nome",
        "es": "Nombre",
        "pl": "Nazwa"
    },
    "ip adress": {
        "en": "ip adress",
        "de": "IP Adresse",
        "ru": "IP адрес",
        "pt": "Endereço de IP",
        "nl": "IP adres",
        "fr": "adresse IP",
        "it": "indirizzo IP",
        "es": "dirección IP",
        "pl": "adres IP"
    },
    "port": {
        "en": "port",
        "de": "Port",
        "ru": "порт",
        "pt": "porta",
        "nl": "haven",
        "fr": "Port",
        "it": "porta",
        "es": "Puerto",
        "pl": "Port"
    },
    "smartname": {
        "en": "smartname",
        "de": "Smartname",
        "ru": "smartname",
        "pt": "smartname",
        "nl": "smartname",
        "fr": "smartname",
        "it": "smartname",
        "es": "nombre inteligente",
        "pl": "smartname"
    },
    "type": {
        "en": "type",
        "de": "Art",
        "ru": "тип",
        "pt": "tipo",
        "nl": "type",
        "fr": "type",
        "it": "genere",
        "es": "tipo",
        "pl": "rodzaj"
    },
    "No spaces in device name": {
        "en": "No spaces in device name",
        "de": "Keine Leerzeichen im Gerätenamen",
        "ru": "Без пробелов в имени устройства",
        "pt": "Nenhum espaço no nome do dispositivo",
        "nl": "Geen spaties in apparaatnaam",
        "fr": "Aucun espace dans le nom de l'appareil",
        "it": "Nessuno spazio nel nome del dispositivo",
        "es": "Sin espacios en el nombre del dispositivo",
        "pl": "Brak spacji w nazwie urządzenia"
    }
};